---
deployment:
  tasks:
    - export DEPLOYPATH=
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp -r dist $DEPLOYPATH
    - /bin/cp -r src $DEPLOYPATH